//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.ServicioEmpleosChile {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicioEmpleosChile", Namespace="http://schemas.datacontract.org/2004/07/ServicioEmpleosChile")]
    [System.SerializableAttribute()]
    public partial class ServicioEmpleosChile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet TableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet Table {
            get {
                return this.TableField;
            }
            set {
                if ((object.ReferenceEquals(this.TableField, value) != true)) {
                    this.TableField = value;
                    this.RaisePropertyChanged("Table");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioEmpleosChile.IServicioEmpleosChile")]
    public interface IServicioEmpleosChile {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetUsuario", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetUsuarioResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetUsuario(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetUsuario", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetUsuarioResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetUsuarioAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/ValUsuario", ReplyAction="http://tempuri.org/IServicioEmpleosChile/ValUsuarioResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile ValUsuario(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/ValUsuario", ReplyAction="http://tempuri.org/IServicioEmpleosChile/ValUsuarioResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> ValUsuarioAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/ValEmpresa", ReplyAction="http://tempuri.org/IServicioEmpleosChile/ValEmpresaResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile ValEmpresa(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/ValEmpresa", ReplyAction="http://tempuri.org/IServicioEmpleosChile/ValEmpresaResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> ValEmpresaAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GuardarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GuardarEmpresaResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GuardarEmpresa(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GuardarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GuardarEmpresaResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GuardarEmpresaAsync(string[] Parametros, string[] valores);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEmpleosChileChannel : WebAPI.ServicioEmpleosChile.IServicioEmpleosChile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEmpleosChileClient : System.ServiceModel.ClientBase<WebAPI.ServicioEmpleosChile.IServicioEmpleosChile>, WebAPI.ServicioEmpleosChile.IServicioEmpleosChile {
        
        public ServicioEmpleosChileClient() {
        }
        
        public ServicioEmpleosChileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEmpleosChileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEmpleosChileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEmpleosChileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetUsuario(string[] Parametros, string[] valores) {
            return base.Channel.GetUsuario(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetUsuarioAsync(string[] Parametros, string[] valores) {
            return base.Channel.GetUsuarioAsync(Parametros, valores);
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile ValUsuario(string[] Parametros, string[] valores) {
            return base.Channel.ValUsuario(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> ValUsuarioAsync(string[] Parametros, string[] valores) {
            return base.Channel.ValUsuarioAsync(Parametros, valores);
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile ValEmpresa(string[] Parametros, string[] valores) {
            return base.Channel.ValEmpresa(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> ValEmpresaAsync(string[] Parametros, string[] valores) {
            return base.Channel.ValEmpresaAsync(Parametros, valores);
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GuardarEmpresa(string[] Parametros, string[] valores) {
            return base.Channel.GuardarEmpresa(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GuardarEmpresaAsync(string[] Parametros, string[] valores) {
            return base.Channel.GuardarEmpresaAsync(Parametros, valores);
        }
    }
}
