//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.ServicioEmpleosChile {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicioEmpleosChile", Namespace="http://schemas.datacontract.org/2004/07/ServicioEmpleosChile")]
    [System.SerializableAttribute()]
    public partial class ServicioEmpleosChile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet TableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet Table {
            get {
                return this.TableField;
            }
            set {
                if ((object.ReferenceEquals(this.TableField, value) != true)) {
                    this.TableField = value;
                    this.RaisePropertyChanged("Table");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioEmpleosChile.IServicioEmpleosChile")]
    public interface IServicioEmpleosChile {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetCandidatosEmpresa", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetCandidatosEmpresaResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetCandidatosEmpresa(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetCandidatosEmpresa", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetCandidatosEmpresaResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetCandidatosEmpresaAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetCiudad", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetCiudadResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetCiudad(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetCiudad", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetCiudadResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetCiudadAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetComuna", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetComunaResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetComuna(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetComuna", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetComunaResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetComunaAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetDetallePublicacion", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetDetallePublicacionResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetDetallePublicacion(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetDetallePublicacion", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetDetallePublicacionResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetDetallePublicacionAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetPais", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetPaisResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetPais();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetPais", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetPaisResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetPaisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetRegion", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetRegionResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetRegion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetRegion", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetRegionResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetRegionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetPlanesEmpresa", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetPlanesEmpresaResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetPlanesEmpresa(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetPlanesEmpresa", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetPlanesEmpresaResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetPlanesEmpresaAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetPublicacionesEmpresa", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetPublicacionesEmpresaResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetPublicacionesEmpresa(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetPublicacionesEmpresa", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetPublicacionesEmpresaResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetPublicacionesEmpresaAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetUsuario", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetUsuarioResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetUsuario(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/GetUsuario", ReplyAction="http://tempuri.org/IServicioEmpleosChile/GetUsuarioResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetUsuarioAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/SetEmpresa", ReplyAction="http://tempuri.org/IServicioEmpleosChile/SetEmpresaResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile SetEmpresa(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/SetEmpresa", ReplyAction="http://tempuri.org/IServicioEmpleosChile/SetEmpresaResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> SetEmpresaAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/SetPublicacionesEmpresa", ReplyAction="http://tempuri.org/IServicioEmpleosChile/SetPublicacionesEmpresaResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile SetPublicacionesEmpresa(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/SetPublicacionesEmpresa", ReplyAction="http://tempuri.org/IServicioEmpleosChile/SetPublicacionesEmpresaResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> SetPublicacionesEmpresaAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/SetUsuario", ReplyAction="http://tempuri.org/IServicioEmpleosChile/SetUsuarioResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile SetUsuario(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/SetUsuario", ReplyAction="http://tempuri.org/IServicioEmpleosChile/SetUsuarioResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> SetUsuarioAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/ValEmpresa", ReplyAction="http://tempuri.org/IServicioEmpleosChile/ValEmpresaResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile ValEmpresa(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/ValEmpresa", ReplyAction="http://tempuri.org/IServicioEmpleosChile/ValEmpresaResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> ValEmpresaAsync(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/ValUsuario", ReplyAction="http://tempuri.org/IServicioEmpleosChile/ValUsuarioResponse")]
        WebAPI.ServicioEmpleosChile.ServicioEmpleosChile ValUsuario(string[] Parametros, string[] valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleosChile/ValUsuario", ReplyAction="http://tempuri.org/IServicioEmpleosChile/ValUsuarioResponse")]
        System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> ValUsuarioAsync(string[] Parametros, string[] valores);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEmpleosChileChannel : WebAPI.ServicioEmpleosChile.IServicioEmpleosChile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEmpleosChileClient : System.ServiceModel.ClientBase<WebAPI.ServicioEmpleosChile.IServicioEmpleosChile>, WebAPI.ServicioEmpleosChile.IServicioEmpleosChile {
        
        public ServicioEmpleosChileClient() {
        }
        
        public ServicioEmpleosChileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEmpleosChileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEmpleosChileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEmpleosChileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetCandidatosEmpresa(string[] Parametros, string[] valores) {
            return base.Channel.GetCandidatosEmpresa(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetCandidatosEmpresaAsync(string[] Parametros, string[] valores) {
            return base.Channel.GetCandidatosEmpresaAsync(Parametros, valores);
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetCiudad(string[] Parametros, string[] valores) {
            return base.Channel.GetCiudad(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetCiudadAsync(string[] Parametros, string[] valores) {
            return base.Channel.GetCiudadAsync(Parametros, valores);
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetComuna(string[] Parametros, string[] valores) {
            return base.Channel.GetComuna(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetComunaAsync(string[] Parametros, string[] valores) {
            return base.Channel.GetComunaAsync(Parametros, valores);
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetDetallePublicacion(string[] Parametros, string[] valores) {
            return base.Channel.GetDetallePublicacion(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetDetallePublicacionAsync(string[] Parametros, string[] valores) {
            return base.Channel.GetDetallePublicacionAsync(Parametros, valores);
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetPais() {
            return base.Channel.GetPais();
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetPaisAsync() {
            return base.Channel.GetPaisAsync();
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetRegion() {
            return base.Channel.GetRegion();
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetRegionAsync() {
            return base.Channel.GetRegionAsync();
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetPlanesEmpresa(string[] Parametros, string[] valores) {
            return base.Channel.GetPlanesEmpresa(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetPlanesEmpresaAsync(string[] Parametros, string[] valores) {
            return base.Channel.GetPlanesEmpresaAsync(Parametros, valores);
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetPublicacionesEmpresa(string[] Parametros, string[] valores) {
            return base.Channel.GetPublicacionesEmpresa(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetPublicacionesEmpresaAsync(string[] Parametros, string[] valores) {
            return base.Channel.GetPublicacionesEmpresaAsync(Parametros, valores);
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile GetUsuario(string[] Parametros, string[] valores) {
            return base.Channel.GetUsuario(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> GetUsuarioAsync(string[] Parametros, string[] valores) {
            return base.Channel.GetUsuarioAsync(Parametros, valores);
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile SetEmpresa(string[] Parametros, string[] valores) {
            return base.Channel.SetEmpresa(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> SetEmpresaAsync(string[] Parametros, string[] valores) {
            return base.Channel.SetEmpresaAsync(Parametros, valores);
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile SetPublicacionesEmpresa(string[] Parametros, string[] valores) {
            return base.Channel.SetPublicacionesEmpresa(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> SetPublicacionesEmpresaAsync(string[] Parametros, string[] valores) {
            return base.Channel.SetPublicacionesEmpresaAsync(Parametros, valores);
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile SetUsuario(string[] Parametros, string[] valores) {
            return base.Channel.SetUsuario(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> SetUsuarioAsync(string[] Parametros, string[] valores) {
            return base.Channel.SetUsuarioAsync(Parametros, valores);
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile ValEmpresa(string[] Parametros, string[] valores) {
            return base.Channel.ValEmpresa(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> ValEmpresaAsync(string[] Parametros, string[] valores) {
            return base.Channel.ValEmpresaAsync(Parametros, valores);
        }
        
        public WebAPI.ServicioEmpleosChile.ServicioEmpleosChile ValUsuario(string[] Parametros, string[] valores) {
            return base.Channel.ValUsuario(Parametros, valores);
        }
        
        public System.Threading.Tasks.Task<WebAPI.ServicioEmpleosChile.ServicioEmpleosChile> ValUsuarioAsync(string[] Parametros, string[] valores) {
            return base.Channel.ValUsuarioAsync(Parametros, valores);
        }
    }
}
